zigpy/zigpy-zigate

- README.md
Update description and links in README.md
> Update description and links in README.md

- README.md
Update README.md to mention releases on PyPI and link to the zigpy-zigate project page there.
> Update README.md to mention releases PyPI

- setup.py
- tests/test_application.py
- tests/test_types.py
- zigpy_zigate/types.py
- zigpy_zigate/zigbee/application.py
Proposed changes to address #4 
Refactor `zigpy_zigate.types.EUI64` so the LSB of IEEE address is stored in the lowest list index and MSB of IEEE is in the highest list index.
> Refactor EUI64 handling.

- README.md
Update README.md with links to specific hardware and related projects
> Update README.md with links to specific hardware and related projects

- README.md
Update README.md removing some text in french for consistency.
Rest of text is all in English and also match the other zigpy libraries.
> Update README.md removing some text in french for consistency

- README.md
Update URL for both travis-ci and coveralls
> Update URL for both travis-ci and coveralls

- setup.py
> Add pypi long description.

- .travis.yml
- setup.py
- tox.ini
- zigpy_zigate/__init__.py
- zigpy_zigate/types.py
0.6.2 Release
Compatibility with `zigpy==0.23.0`
> 0.6.2 Release

- README.md
Update README.md to mention Open Lumi Gateway with ZiGate firmware, working as per https://github.com/zigpy/zigpy-zigate/issues/59
> Update README.md to mention Open Lumi Gateway with ZiGate firmware

- README.md
Adding https://github.com/doudz/zigate as developer reference as suggested in https://github.com/zigpy/zigpy-zigate/pull/58
> Update README.md with developer reference

- README.md
Update README.md with extended ZiGate Flasher Firmware Tool description
> Update README.md with extended ZiGate Flasher Firmware Tool description

- README.md
Updated related projects in README.md as copied with https://github.com/zigpy/zigpy/blob/dev/README.md with the exception of Zigpy Deconz Parser as that is not related to zigate.
> Updated related projects in README.md

- README.md
Update README.md with 3.1d firmware recommendations or requirements
> Update README.md with 3.1d firmware recommendations or requirements

- README.md
Update README.md with link to official firmware releases since seen questions in zigpy-zigate about links to firmware.
> Update README.md with link to official firmware releases

- README.md
Update README.md adding ZiGate-Ethernet to list of compatible hardware.
Discussion here -> https://github.com/zigpy/zigpy/discussions/790
> Update README.md adding ZiGate-Ethernet to list

- setup.py
- tests/test_api.py
- tests/test_application.py
- tests/test_types.py
- zigpy_zigate/__init__.py
- zigpy_zigate/api.py
- zigpy_zigate/types.py
- zigpy_zigate/zigbee/application.py
> 0.9.0 Release

- zigpy_zigate/__init__.py
- zigpy_zigate/types.py
- zigpy_zigate/zigbee/application.py
> 0.10.1 Release

- tests/async_mock.py
- tests/test_api.py
- tests/test_application.py
- tests/test_uart.py
- zigpy_zigate/__init__.py
- zigpy_zigate/api.py
- zigpy_zigate/zigbee/application.py
> 0.10.2 Release

- tests/test_application.py
- zigpy_zigate/zigbee/application.py
This restores the functionality of earlier zigpy-zigate releases for users who cannot upgrade their adapter.
https://github.com/home-assistant/core/issues/80130.
> Always enable ACKs on older firmwares

- tests/test_application.py
- zigpy_zigate/zigbee/application.py
https://github.com/home-assistant/core/issues/91467
> Disable energy scanning and implement channel migration
