setup.py
tests/test_api.py
tests/test_application.py
tests/test_uart.py
tox.ini
zigpy_zigate/api.py
zigpy_zigate/config.py
zigpy_zigate/uart.py
zigpy_zigate/zigbee/application.py

Implement new zigpy initialization and support for radio lib configuration schemas in https://github.com/zigpy/zigpy/commits/new-zigpy-init/dev
This would allow each radio lib to extend the zigpy configuration schema by adding radio specific configuration options.
Corresponding HA changes are currently in https://github.com/Adminiuga/home-assistant/tree/experimental/new-zigpy-init
I don't have a zigate so can't test, but once tested I'm going to publish new zigpy version.

New zigpy initialization routine

---

.github/workflows/publish-to-pypi.yml

Automatically publish packages to pypi index on branch tagging.

Add GitHub PyPa GitHub action

---

setup.py
tests/test_api.py
tests/test_application.py
tests/test_uart.py
tox.ini
zigpy_zigate/__init__.py
zigpy_zigate/api.py
zigpy_zigate/config.py
zigpy_zigate/uart.py
zigpy_zigate/zigbee/application.py

Merge PR to add the following:
#32 A "lightweight" probe method to validate there's is a correct device on the selected port. If we get a reply to set_raw_mode() command, then we consider a correct device on the given port.
HA Core would use this probe method (instead of full blown zigpy load/startup) to validate config entry data.
#30 Implement new zigpy initialization and support for radio lib configuration schemas in https://github.com/zigpy/zigpy/commits/new-zigpy-init/dev
This would allow each radio lib to extend the zigpy configuration schema by adding radio specific configuration options. Corresponding 
HA changes are currently in https://github.com/Adminiuga/home-assistant/tree/experimental/new-zigpy-init

New zigpy init/dev

---

.travis.yml
setup.py
tox.ini
zigpy_zigate/types.py

Drop python 3.6
Use own hex representation for NWK class.
Dependency on zipgy, instead of zigpy-homeassistant

Syncup with zigpy==0.23.0 changes

---

README.md

@doudz the https://github.com/Neonox31/zigate and https://github.com/nouknouk/node-zigate libraries by @Neonox31 and @nouknouk respectively can help developers in understanding the protocol and implementation of ZiGate adapters. 
Neonox31's zigate library converts ZiGate frames into human readable messages and vice versa, and the node-zigate project by nouknouk  aims to provide low-level and high-level APIs for managing the Zigate USB TTL adapter in node.js

Update README.md with two more developer references

---

setup.py

otherwise it would not match and try to install a package called 'tests' at top level which is forbidden.
Thanks.
\B.

Update setup.py, fix bad exclude mask

---

setup.py

Bump up dependencies on pyserial and pyserial-asyncio for projects other projects that use this library but are not Home Assistant.
Adminiuga did the same dependency version bump for Home Assistant in https://github.com/home-assistant/core/pull/44089
pyserial-asyncio depends on pyserial and this bumps pyserial-asyncio to 0.5 version release and pyserial to 3.5 version release.
https://github.com/pyserial/pyserial-asyncio/releases/tag/v0.5
https://github.com/pyserial/pyserial/releases/tag/v3.5

Bump up dependencies on pyserial and pyserial-asyncio

---

zigpy_zigate/zigbee/application.py

Hi @doudz,
#75 fix is not working because of missing defaults on parameters "hops" and "non_member_radius". 
This pull request fix this.
Thank you for your time and Happy new year !

Fix mrequest implementation - missing parameter defaults

---

zigpy_zigate/zigbee/application.py

This patch adds initial support for other firmware for NXP chips jn5168/5169 and others that has similar to zigate protocol.
My comrades are working on the firmware that uses "true" raw mode for NXP chips.
https://github.com/openlumi/JN-ZigbeeNodeControlBridge-firmware
It uses raw mode for join requests too, so it is required to parse that frame to support joining. 
It is supported in zigbee2mqtt application https://github.com/Koenkk/zigbee-herdsman/blob/6d7adca45f3154bac522dd33a2bc64f908a30c3c/src/adapter/zigate/driver/zigate.ts#L316-L324
I'd like to add support to ZHA in Home Assistant.

Working with pure raw mode of NXP chip

---

README.md

Updated URLs and descriptions with some info on latest "ZiGate +" / "ZiGate v2" products.
This should also close https://github.com/zigpy/zigpy-zigate/issues/86 as added this mentioning about GPIO header compatibility:
- [PiZiGate + / PiZiGate (ZiGate HAT/Shield module for Raspberry Pi compatible GPIO header)](https://zigate.fr/produit/pizigatev2/)
- Tip! PiZiGate are not limited to Raspberry Pi series as works with all computers with a Raspberry Pi compatible GPIO header.

Update README.md URLs and descriptions for ZiGate v2 products

---

tests/test_types.py
zigpy_zigate/api.py
zigpy_zigate/zigbee/application.py

I assume this appeared since I updated my zigate 1 from `3.1d` to `3.21` this morning.
I saw a strange closed PR here: https://github.com/zigpy/zigpy-zigate/pull/107 and the underlying issue is this one I guess: https://github.com/zigpy/zigpy-zigate/issues/104
Is there a way to easily test what I did in home assistant? I could copy paste the api.py and application.py into the home assistant folder but it seems a little by messy right?

handle response 0x8012

---

setup.py
tests/test_api.py
tests/test_application.py
tests/test_types.py
zigpy_zigate/api.py
zigpy_zigate/types.py
zigpy_zigate/zigbee/application.py

zigpy-zigate is the last radio library remaining.
Parent issues:
- https://github.com/zigpy/zigpy/issues/842
- https://github.com/zigpy/zigpy/pull/848
- https://github.com/zigpy/zigpy-cli/pull/2
@pipiche38 I do not have a ZiGate so this code is untested beyond the unit tests. They pass with the modified version of zigpy.

Implement the new zigpy radio API

---

setup.py
tests/test_api.py
zigpy_zigate/common.py
zigpy_zigate/tools/flasher.py
zigpy_zigate/uart.py

https://github.com/home-assistant/core/issues/75967
`gpiozero` is pure-Python and can be installed on any platform, removing the need for the conditional requirements in the `setup.py` file.
I don't have a GPIO or DIN ZiGate to test with so this is a blind implementation. It should work but I would appreciate someone testing it out.

Switch from `RPi.GPIO` to `gpiozero`

---

setup.py
tests/test_api.py
zigpy_zigate/__init__.py
zigpy_zigate/common.py
zigpy_zigate/tools/flasher.py
zigpy_zigate/uart.py

0.9.1 Release

---

tests/test_uart.py
zigpy_zigate/common.py

#125 contained a last-minute typo that was not caught by unit tests.

Fix typo in GPIO pin configuration kwargs and add unit test

---

tests/test_application.py
zigpy_zigate/zigbee/application.py

`disconnect` should work even if the port is already disconnected (i.e. in a context manager where it's always called to clean up).

Ensure `disconnect` can be called multiple times

---

tests/test_application.py
tests/test_uart.py
zigpy_zigate/__init__.py
zigpy_zigate/common.py
zigpy_zigate/zigbee/application.py

0.9.2 Release

---

.github/workflows/publish-to-pypi.yml
.github/workflows/tests.yml
setup.py
zigpy_zigate/api.py
zigpy_zigate/types.py
zigpy_zigate/uart.py
zigpy_zigate/zigbee/application.py

Once https://github.com/zigpy/zigpy/pull/1043 is merged and a new zigpy version is released this PR can be merged.
Prior to this change, broadcast was not implemented in zigpy-zigate. It should be functional now that the correct address mode is implemented, but it is not: the packet is correctly sent with the appropriate address mode and a non-zero radius, but I cannot see it with a sniffer.
This has the unfortunate side effect of not allowing you to permit joins through any device other than the coordinator.
@pipiche38

Implement new zigpy packet API

---

.github/workflows/publish-to-pypi.yml
.github/workflows/tests.yml
setup.py
zigpy_zigate/__init__.py
zigpy_zigate/api.py
zigpy_zigate/types.py
zigpy_zigate/uart.py
zigpy_zigate/zigbee/application.py

0.10.0 Release

---

zigpy_zigate/types.py
zigpy_zigate/zigbee/application.py

"Fixes" #133 and thus https://github.com/home-assistant/core/issues/79720.

Ignore firmware 3.1d send failures

---

tests/async_mock.py
tests/test_api.py
tests/test_application.py
tests/test_uart.py
zigpy_zigate/zigbee/application.py

Fix startup version command handling

---

tests/test_application.py
zigpy_zigate/api.py
zigpy_zigate/zigbee/application.py

Group requests don't work when downgrading to 2022.9.7 so this change is entirely to prevent an error from being thrown:
```Python
2022-10-10 12:24:45.058 DEBUG (MainThread) [zigpy_zigate.zigbee.application] Sending packet ZigbeePacket(src=None, src_ep=1, dst=AddrModeAddress(addr_mode=<AddrMode.Group: 1>, address=0x0002), dst_ep=None, source_route=None, extended_timeout=False, tsn=37, profile_id=260, cluster_id=6, data=Serialized[b'\x01%\x00'], tx_options=<TransmitOptions.NONE: 0>, radius=0, non_member_radius=3, lqi=None, rssi=None)
2022-10-10 12:24:45.058 DEBUG (MainThread) [zigpy_zigate.api] Sending CommandId.SEND_RAW_APS_DATA_PACKET (b'\x01\x00\x02\x01\x00\x00\x06\x01\x04\x00\x00\x03\x01%\x00'), waiting for status: True, waiting for response: None
2022-10-10 12:24:45.058 DEBUG …
```

Fix exception when sending group requests

---

tests/test_application.py
zigpy_zigate/__init__.py
zigpy_zigate/zigbee/application.py

0.10.3 Release

---

tests/test_application.py
zigpy_zigate/__init__.py
zigpy_zigate/zigbee/application.py

0.11.0 Release
